# Action for building and testing code
---
name: android-build
on: # yamllint disable-line rule:truthy rule:comments
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        java-version: [17]
        distribution: [corretto]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
      - name: Setup Android
        uses: android-actions/setup-android@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache
        id: create-gradle-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ env.cache-name }}-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.properties') }}
      - name: Test project
        run: ./gradlew test
